from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text()
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{path}: expected one match, got {count}: {old[:120]!r}")
    p.write_text(text.replace(old, new, 1))


replace_once(
    "docs/ARCHITECTURE.md",
    "`EnginePrivilegedRequestTracker` extends that Network correlation identity with the exact raw target, canonical pinned-Rarog method and bounded headers, exact optional bounded body, and canonical pinned-Rarog request mode, credentials mode, redirect mode and destination. Compatibility registration binds Rarog's exact `Cors` / `SameOrigin` / `Follow` / `Empty` defaults; the full request-parts path accepts those canonical enums directly rather than parsing browser-owned strings. Custom `RequestDestination::Other` data is retained exactly but capped at 256 bytes before tracker slot/body-budget/identity consumption and is never serialized in `Debug`. All fields participate in one-shot equality, so same-ID substitution burns the request after centrally releasing body accounting. These fields remain correlation metadata only: even an exact current same-Site request is denied as unsupported, and no CORS/Fetch behavior, capability grant or Host network execution follows from their presence.\n",
    "`EnginePrivilegedRequestTracker` extends that Network correlation identity with the exact raw target, canonical pinned-Rarog method and bounded headers, exact optional bounded body, canonical pinned-Rarog request mode, credentials mode, redirect mode and destination, plus an exact bounded response-body byte limit. Compatibility registration binds Rarog's exact `Cors` / `SameOrigin` / `Follow` / `Empty` defaults and the pinned `DEFAULT_MAX_RESPONSE_BODY_BYTES`; the explicit full path accepts canonical envelope values plus a response limit in `1..=MAX_PRIVILEGED_NETWORK_RESPONSE_BODY_BYTES`. That Zorya maximum is deliberately the pinned Rarog default (64 MiB at this revision), so correlation state cannot carry an effectively unbounded response budget into a later execution slice. Custom `RequestDestination::Other` data remains capped at 256 bytes and Debug-redacted. Every envelope field, including the response limit, participates in one-shot equality, so same-ID substitution burns the request after centrally releasing request-body accounting. Response-limit binding is correlation/budget identity only: Zorya does not allocate, buffer or enforce response bytes here, and even an exact current same-Site request remains unsupported with no CORS/Fetch behavior, capability grant or Host network execution.\n",
)

roadmap_old = "mode/credentials/redirect/destination binding is correlation only, while response-limit binding, Origin-header synthesis, CORS/Fetch execution and all capability/Host operations remain future work;"
roadmap_new = "mode/credentials/redirect/destination binding and the exact response-body limit are correlation only. Compatibility paths bind the pinned Rarog 64 MiB default; the explicit path accepts only `1..=MAX_PRIVILEGED_NETWORK_RESPONSE_BODY_BYTES`, where that product maximum equals the pinned Rarog default, and invalid limits fail before request-ID, pending-slot or request-body-budget consumption. Same-ID response-limit substitution burns the stored request after request-body accounting is released, and the numeric limit may appear as safe Debug metadata. No response allocation/buffering/enforcement, Origin-header synthesis, CORS/Fetch execution or capability/Host operation is introduced;"
replace_once("docs/ROADMAP.md", roadmap_old, roadmap_new)

replace_once(
    "docs/Z4_SECURITY_BOUNDARIES.md",
    "Generic registration captures the exact committed-document authority snapshot plus a product request kind, but it cannot create a source-only `Network` entry: `register(..., Network)` fails with `NetworkTargetRequired`. Network attempts require and clone the Host-minted exact committed source (authority plus canonical Origin), binding that exact source to the raw requested target, a canonical pinned-Rarog `FetchMethod`, a bounded canonical pinned-Rarog `HeaderList`, an exact optional bounded request body, and canonical pinned-Rarog `RequestMode`, `CredentialsMode`, `RedirectMode` and `RequestDestination`. The existing `register_network`, `register_network_with_headers`, `register_network_with_method`, and `register_network_with_method_and_headers` paths remain explicit no-body conveniences; `register_network_with_method_headers_and_body` preserves the pinned Rarog Fetch defaults (`Cors`, `SameOrigin`, `Follow`, `Empty`), while `register_network_with_request_parts` binds the full current envelope without adding an unbound path. Zorya does not add another HTTP-method or header parser or normalization table: method canonicalization/token validation/CONNECT-TRACE-TRACK rejection plus header-name/value validation and normalization remain Rarog Fetch semantics.\n",
    "Generic registration captures the exact committed-document authority snapshot plus a product request kind, but it cannot create a source-only `Network` entry: `register(..., Network)` fails with `NetworkTargetRequired`. Network attempts require and clone the Host-minted exact committed source (authority plus canonical Origin), binding that exact source to the raw requested target, a canonical pinned-Rarog `FetchMethod`, a bounded canonical pinned-Rarog `HeaderList`, an exact optional bounded request body, canonical pinned-Rarog `RequestMode`, `CredentialsMode`, `RedirectMode` and `RequestDestination`, and an exact bounded response-body byte limit. The existing `register_network`, `register_network_with_headers`, `register_network_with_method`, and `register_network_with_method_and_headers` paths remain explicit no-body conveniences; `register_network_with_method_headers_and_body` preserves the pinned Rarog Fetch envelope defaults (`Cors`, `SameOrigin`, `Follow`, `Empty`), while `register_network_with_request_parts` also binds the pinned `DEFAULT_MAX_RESPONSE_BODY_BYTES`. `register_network_with_request_parts_and_response_limit` is the explicit full path and accepts only response limits in `1..=MAX_PRIVILEGED_NETWORK_RESPONSE_BODY_BYTES`. Zorya does not add another HTTP-method or header parser or normalization table: method canonicalization/token validation/CONNECT-TRACE-TRACK rejection plus header-name/value validation and normalization remain Rarog Fetch semantics.\n",
)

replace_once(
    "docs/Z4_SECURITY_BOUNDARIES.md",
    "The tracker retains at most 4096 bytes of target text per Network request (`MAX_PRIVILEGED_NETWORK_TARGET_BYTES`), at most 64 canonical header entries (`MAX_PRIVILEGED_NETWORK_HEADERS`), at most 16 KiB of aggregate canonical Rarog header bytes (`MAX_PRIVILEGED_NETWORK_HEADER_BYTES`), and at most 1 MiB of body bytes in any one pending Network request (`MAX_PRIVILEGED_NETWORK_BODY_BYTES`). Incoming canonical headers are re-bound through `HeaderList::iter()` plus `HeaderList::append()` into fixed product limits, so caller-selected `HeaderList` capacities are not part of request identity. Request bodies are retained as exact immutable shared bytes so cloning a request handle does not duplicate the body allocation; absence and a present-but-empty body remain distinct request states. Body compatibility reuses the pinned Rarog `FetchMethod::permits_body()` contract, so present bodies on GET/HEAD are rejected without a second Zorya method table. `RequestDestination::Other(String)` is retained byte-for-byte but capped at 256 bytes (`MAX_PRIVILEGED_NETWORK_DESTINATION_BYTES`) before request-ID allocation, pending-slot use or body-budget consumption. Header/body/destination overflow, aggregate body-budget overflow and body-accounting arithmetic overflow fail closed before request-ID allocation or pending-slot consumption.\n",
    "The tracker retains at most 4096 bytes of target text per Network request (`MAX_PRIVILEGED_NETWORK_TARGET_BYTES`), at most 64 canonical header entries (`MAX_PRIVILEGED_NETWORK_HEADERS`), at most 16 KiB of aggregate canonical Rarog header bytes (`MAX_PRIVILEGED_NETWORK_HEADER_BYTES`), and at most 1 MiB of body bytes in any one pending Network request (`MAX_PRIVILEGED_NETWORK_BODY_BYTES`). Incoming canonical headers are re-bound through `HeaderList::iter()` plus `HeaderList::append()` into fixed product limits, so caller-selected `HeaderList` capacities are not part of request identity. Request bodies are retained as exact immutable shared bytes so cloning a request handle does not duplicate the body allocation; absence and a present-but-empty body remain distinct request states. Body compatibility reuses the pinned Rarog `FetchMethod::permits_body()` contract, so present bodies on GET/HEAD are rejected without a second Zorya method table. `RequestDestination::Other(String)` is retained byte-for-byte but capped at 256 bytes (`MAX_PRIVILEGED_NETWORK_DESTINATION_BYTES`) before request-ID allocation, pending-slot use or body-budget consumption. The correlated response limit is a fixed-size scalar but is still bounded: `MAX_PRIVILEGED_NETWORK_RESPONSE_BODY_BYTES` equals the pinned Rarog `DEFAULT_MAX_RESPONSE_BODY_BYTES` (64 MiB at this revision), and zero or larger explicit values fail closed before request-ID allocation, pending-slot use or request-body-budget consumption. Header/body/destination/response-limit overflow, aggregate body-budget overflow and body-accounting arithmetic overflow therefore fail before request-ID allocation or pending-slot consumption.\n",
)

replace_once(
    "docs/Z4_SECURITY_BOUNDARIES.md",
    "Raw targets, canonical source-Origin/host/port serialization, header names/values, request-body contents and `RequestDestination::Other` contents are process-local, are not persisted, and are deliberately omitted from the Network handle's `Debug` output. Only target byte count, header count/aggregate header bytes, body-present/body-byte metadata, finite mode/credentials/redirect values, destination kind and custom-destination byte count may be shown. The canonical HTTP method is non-secret correlation data and may appear in `Debug` output. The aggregate body budget accounts bytes while requests are pending in the tracker; cloned request handles share the same immutable body allocation rather than multiplying retained body bytes per clone.\n",
    "Raw targets, canonical source-Origin/host/port serialization, header names/values, request-body contents and `RequestDestination::Other` contents are process-local, are not persisted, and are deliberately omitted from the Network handle's `Debug` output. Only target byte count, header count/aggregate header bytes, body-present/body-byte metadata, finite mode/credentials/redirect values, destination kind/custom-destination byte count and the numeric response-body limit may be shown. The canonical HTTP method and response limit are non-secret correlation/budget metadata. The aggregate request-body budget accounts bytes while requests are pending in the tracker; cloned request handles share the same immutable body allocation rather than multiplying retained body bytes per clone.\n",
)

replace_once(
    "docs/Z4_SECURITY_BOUNDARIES.md",
    "Network registration remains correlation only. It accepts but cannot fabricate the Host-minted source; it does not parse a Network target, revalidate source state, synthesize an HTTP `Origin` header, create a Rarog `FetchRequest` or authorize an operation. Deferring target parsing until consumption preserves the fail-closed order established by `preflight_network_target`: a request staged before source replacement is rejected as stale before malformed, unsupported-scheme or cross-Site target classification can run. Binding a canonical method, headers, body, mode, credentials, redirect and destination does not execute the method, interpret header/body semantics beyond Rarog's method/body compatibility contract, enact Fetch mode/credential/redirect/destination behavior, or start a network operation.\n",
    "Network registration remains correlation only. It accepts but cannot fabricate the Host-minted source; it does not parse a Network target, revalidate source state, synthesize an HTTP `Origin` header, create a Rarog `FetchRequest` or authorize an operation. Deferring target parsing until consumption preserves the fail-closed order established by `preflight_network_target`: a request staged before source replacement is rejected as stale before malformed, unsupported-scheme or cross-Site target classification can run. Binding a canonical method, headers, body, mode, credentials, redirect, destination and bounded response-body limit does not execute the method, interpret header/body semantics beyond Rarog's method/body compatibility contract, enact Fetch mode/credential/redirect/destination behavior, allocate or buffer response data, enforce a response stream, or start a network operation.\n",
)

replace_once(
    "docs/Z4_SECURITY_BOUNDARIES.md",
    "Same-ID source/kind/method/header/body/mode/credentials/redirect/destination/target mismatches burn the stored slot rather than making it reusable; this includes the distinction between no body and a present-but-empty body. Generic exact requests invoke the deny-by-default source preflight. Exact fully envelope-bound Network requests invoke the canonical Network target preflight with the stored raw target. Consequently copied/cloned handles cannot replay through the same tracker or a replacement tracker, cross-EngineHost numeric counter reuse cannot revive an old request, and swapping method, headers, body, mode, credentials, redirect, destination or target on a captured request cannot redirect its later operation/policy identity.\n",
    "Same-ID source/kind/method/header/body/mode/credentials/redirect/destination/response-limit/target mismatches burn the stored slot rather than making it reusable; this includes the distinction between no body and a present-but-empty body. Generic exact requests invoke the deny-by-default source preflight. Exact fully envelope-bound Network requests invoke the canonical Network target preflight with the stored raw target. Consequently copied/cloned handles cannot replay through the same tracker or a replacement tracker, cross-EngineHost numeric counter reuse cannot revive an old request, and swapping method, headers, body, mode, credentials, redirect, destination, response limit or target on a captured request cannot redirect its later operation/policy identity.\n",
)

replace_once(
    "docs/Z4_SECURITY_BOUNDARIES.md",
    "Even a current exact same-site fully envelope-bound Network request still ends at `DeniedUnsupported`. The lifecycle adds no allow result, Rarog broker dependency, capability grant, Host network operation, clipboard action or IPC authority. Mode, credentials, redirect and destination are now bound only as canonical correlation metadata; response-limit binding remains outside this slice. Origin-header synthesis, CORS enforcement and Fetch execution are also not introduced. Streaming/file uploads are also not introduced. A later actual brokering path must accept only fully reviewed request envelopes, preserve consume-once semantics and perform the separately reviewed policy/revalidation immediately before any grant.\n",
    "Even a current exact same-site fully envelope-bound Network request still ends at `DeniedUnsupported`. The lifecycle adds no allow result, Rarog broker dependency, capability grant, Host network operation, clipboard action or IPC authority. Mode, credentials, redirect, destination and the bounded response-body limit are bound only as canonical correlation/budget metadata. Response allocation, buffering and enforcement, Origin-header synthesis, CORS enforcement and Fetch execution are not introduced. Streaming/file uploads are also not introduced. A later actual brokering path must accept only fully reviewed request envelopes, preserve consume-once semantics and perform the separately reviewed policy/revalidation immediately before any grant.\n",
)

replace_once(
    "docs/Z4_SECURITY_BOUNDARIES.md",
    "- Network response-limit binding and any execution/policy semantics for the bound request mode, credentials, redirect or destination;\n",
    "- Network response allocation, buffering or enforcement and any execution/policy semantics for the bound request mode, credentials, redirect, destination or response-body limit;\n",
)

# Clean two long source comments while this finalizer is already validating the tree.
p = Path("src/privileged_request.rs")
s = p.read_text()
s = s.replace(
    "/// canonical headers, exact optional bounded body, canonical Fetch envelope metadata, exact response-body\n/// byte limit and raw target.\n",
    "/// canonical headers, exact optional bounded body, canonical Fetch envelope metadata, exact\n/// response-body byte limit and raw target.\n",
    1,
)
s = s.replace(
    "    /// Same-ID source, method, headers, body, mode, credentials, redirect, destination, response limit or target\n"
    "    /// mismatches burn the stored slot. Stored body\n",
    "    /// Same-ID source, method, headers, body, mode, credentials, redirect, destination, response\n"
    "    /// limit or target mismatches burn the stored slot. Stored body\n",
    1,
)
s = s.replace(
    "    /// metadata and response limit are correlation data for a later reviewed Fetch/broker path and are\n"
    "    /// not executed or enforced here.\n",
    "    /// metadata and response limit are correlation data for a later reviewed Fetch/broker path and\n"
    "    /// are not executed or enforced here.\n",
    1,
)
p.write_text(s)
